imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        handler_id:  ~
        storage_id: session.storage.filesystem
        name: MOCKSESSID
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

liip_functional_test: ~
