hwi_oauth:
    connect:
        account_connector: my_user_provider
    firewall_names: [main]
    fosub:
        username_iterations: 30
        properties:
            facebook: facebookId
            google:   googleId
    resource_owners:
        facebook:
            type:                facebook
            client_id:           %facebook_app_id%
            client_secret:       %facebook_app_secret%
            scope:               "email"
        google:
            type:                 google
            client_id:            %google_app_id%
            client_secret:        %google_app_secret%
            scope:                "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"

