hwi_oauth:
    connect:
        account_connector: my_user_provider
    firewall_names: [main]
    fosub:
        username_iterations: 30
        properties:
            facebook:  facebookId
            google:    googleId
            vk:        vkId
    resource_owners:
        facebook:
            type:                facebook
            client_id:           %facebook_app_id%
            client_secret:       %facebook_app_secret%
            scope:               "email"
            infos_url:           "https://graph.facebook.com/me?fields=id,first_name,last_name,email"
        google:
            type:                 google
            client_id:            %google_app_id%
            client_secret:        %google_app_secret%
            scope:                "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
        vk:
            type:                 vkontakte
            client_id:            %vk_app_id%
            client_secret:         %vk_app_secret%
