# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    fos_user.doctrine_registry:
        alias: doctrine

    doctrine.processing_manager_request_listener:
        class: AppBundle\EventListener\ProcessingManagerRequestListener
        tags:
            - { name: doctrine.event_listener, event: postUpdate, method: postUpdate  }
