vich_uploader:
    db_driver: orm
    mappings:
        group_image:
            uri_prefix:         /images/groups
            upload_destination: %kernel.root_dir%/../web/images/groups
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
