services:
    admin.group:
        class: AppBundle\Admin\GroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Контент", label: "Гурти" }
        arguments:
            - ~
            - AppBundle\Entity\Group
            - ~

    admin.genre:
        class: AppBundle\Admin\GenreAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Контент", label: "Жанри" }
        arguments:
            - ~
            - AppBundle\Entity\Genre
            - ~

    admin.event:
        class: AppBundle\Admin\EventAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Контент", label: "Концерти" }
        arguments:
            - ~
            - AppBundle\Entity\Event
            - ~

