services:
    app.vich_uploader_directory_namer:
        class: AppBundle\Service\DirectoryNamerService

    my_user_provider:
        class: AppBundle\Security\Provider\OAuthUserProvider
        arguments:
            - "@fos_user.user_manager"
            - { facebook: facebookId, google: googleId, vk: vkId }

    app.entity_listener.request_manager:
        class: AppBundle\EntityListener\RequestManagerListener
        tags:
            -  { name: doctrine.orm.entity_listener }
