services:
    app.event:
        class: AppBundle\Service\EventService
        arguments:
            - @doctrine.orm.default_entity_manager

    app.group:
        class: AppBundle\Service\GroupService
        arguments:
            - @doctrine.orm.default_entity_manager

    app.manager:
        class: AppBundle\Service\ManagerService
        arguments:
            - @doctrine.orm.default_entity_manager

    app.user:
        class: AppBundle\Service\UserService
        arguments:
            - @doctrine.orm.default_entity_manager

    app.entity_listener.request_manager:
        class: AppBundle\EntityListener\RequestManagerListener
        tags:
            -  { name: doctrine.orm.entity_listener }

    app.vich_uploader_directory_namer:
        class: AppBundle\Service\DirectoryNamerService

    my_user_provider:
        class: AppBundle\Security\Provider\OAuthUserProvider
        arguments:
            - "@fos_user.user_manager"
            - { facebook: facebookId, google: googleId, vk: vkId }

