services:
    my_user_provider:
        class: AppBundle\Security\Provider\OAuthUserProvider
        arguments:
            - "@fos_user.user_manager"
            - { facebook: facebookId, google: googleId, vk: vkId }
